### ISSUE TITLE
Missing files ?

### ISSUE THREAD

**Issue by AlucardVoss** [maikel233/X-HOOK-For-CSGO#2]
The source is unable to compile because there are files missing

- Cannot open include file: 'OverrideConfig.h': No such file or directory
- Cannot open include file: 'Console.h': No such file or directory
- Cannot open source file: 'OverrideConfig.cpp': No such file or directory 
- Cannot open source file: 'Console.cpp': No such file or directory

**Comment by maikel233** [comment]
Well if you check the Overrideconfig.h and .cpp you can see those files are empty.

The hook is located in Hooks.cpp.
