### ISSUE TITLE
Please help. Cannot open include file

### ISSUE THREAD

**Issue by DaRealSh0T** [maikel233/X-HOOK-For-CSGO#3]
![image](https://user-images.githubusercontent.com/19959465/49842406-cb6fff00-fd91-11e8-8623-150b8450bbb3.png)
could you please help me with this problem?

**Comment by SeeSoftware** [comment]
Actually there are missing files, and even if you fix the include errors (what i did) you are still left with a broken project

**Comment by maikel233** [comment]
All those files are included.

TIP!
Check your project settings...  Because it's trying to check another Path...

**Comment by DaRealSh0T** [comment]
Could you help? what should I look for in project settings?
