### ISSUE TITLE
helpp

### ISSUE THREAD

**Issue by NNiX1** [maikel233/X-HOOK-For-CSGO#5]
im trying to atleast build it but i cant seem to find a problem getting errors about imgui even i included it 10 times in different ways + included exmaple etc any help?

error C2065: 'ImGuiSetCond_Always': undeclared identifier
error C2065: 'ImGuiSetCond_FirstUseEver': undeclared identifier
error C2660: 'ImGui::Begin': function does not take 5 arguments

**Comment by maikel233** [comment]
Sorry!!! very late reply but there was a issue with this build on github uploaded a new one.
