### ISSUE TITLE
i get tons of errors when trying to build

### ISSUE THREAD

**Issue by birdlip** [maikel233/X-HOOK-For-CSGO#6]
https://x0.at/q1f.png

**Comment by maikel233** [comment]
I would suggest to make some applications of your own before building someones project... 
 Anyway

Solution -> Properties -> debug configuration -> Directories

Edit your Include and libary directory's there.

**Comment by birdlip** [comment]
could i learn from you
?

**Comment by birdlip** [comment]
i did that and i still get errors[]( https://x0.at/_6H.png)

**Comment by birdlip** [comment]
[photo](https://x0.at/_6H.png)
[photo2](https://x0.at/u18.png)
https://pastebin.com/5YfAbYDv
