### ISSUE TITLE
crash when inject

### ISSUE THREAD

**Issue by Utkukck11** [maikel233/X-HOOK-For-CSGO#8]
debug pi
![Screenshot (373)](https://user-images.githubusercontent.com/61580513/184354332-001efd68-9c99-46cf-b1ca-75a796cad653.png)
c

**Comment by Utkukck11** [comment]
i fixed createmove input and keyvalues

**Comment by Utkukck11** [comment]
keyvalues? `typedef void(__thiscall* orgGameFunc_LoadFromBuffer)(void* thisptr, const char* resourceName, const char* pBuffer, /*IBaseFileSystem**/void* pFileSystem, const char* pPathID, void* pfnEvaluateSymbolProc);
orgGameFunc_LoadFromBuffer pLoadFromBuffer;

void Util::LoadFromBuffer(KeyValues* pKeyValues, const char* resourceName, const char* pBuffer, /*IBaseFileSystem**/void* pFileSystem = nullptr, const char* pPathID = NULL, void* pfnEvaluateSymbolProc = nullptr)
{
	auto dwLoadFromBuffer = FindPattern("client.dll", "55 8B EC 83 E4 F8 83 EC 34 53 8B 5D 0C 89"); //55 8B EC 83 E4 F8 83 EC 34 53 8B 5D 0C 89

	if (!pLoadFromBuffer)
		pLoadFromBuffer = reinterpret_cast<orgGameFunc_LoadFromBuffer>(dwLoadFromBuffer);

	pLoadFromBuffer(pKeyValues, resourceName, pBuffer, pFileSystem, pPathID, pfnEvaluateSymbolProc);
}


void Util::InitKeyValues(KeyValues* keyValues, char const* name, int, int)
{
	DWORD dwFunction = (DWORD)KeyValues_KeyValues;
	__asm
	{
		push name
		mov ecx, keyValues
		call dwFunction
	}



}

/*void Util::LoadFromBuffer(KeyValues* keyValues, char const* resourceName, const char* pBuffer, /*IBaseFileSystem*void* pFileSystem, const char* pPathID, void* pfnEvaluateSymbolProc)
{
	DWORD dwFunction = (DWORD)KeyValues_LoadFromBuffer;

	__asm
	{
		push 0
		push 0
		push 0
		push pBuffer
		push resourceName
		mov ecx, keyValues
		call dwFunction
	}
}*/
int RandomInt2(int min, int max)
{
	return rand() % (max - min + 1) + min;
}
IMaterial* Util::CreateMaterial(std::string type, std::string texture, bool ignorez, bool nofog, bool model, bool nocull, bool halflambert)
{
	std::stringstream materialData;
	materialData << "\"" + type + "\"\n"
		"{\n"
		"\t\"$basetexture\" \"" + texture + "\"\n"
		"\t\"$ignorez\" \"" + std::to_string(ignorez) + "\"\n"
		"\t\"$nofog\" \"" + std::to_string(nofog) + "\"\n"
		"\t\"$model\" \"" + std::to_string(model) + "\"\n"
		"\t\"$nocull\" \"" + std::to_string(nocull) + "\"\n"
		"\t\"$halflambert\" \"" + std::to_string(halflambert) + "\"\n"
		"}\n" << std::flush;

	std::string materialName = "XHOOK" + std::to_string(RandomInt2(10, 100000));
	KeyValues* keyValues = new KeyValues(materialName.c_str());

	Util::InitKeyValues(keyValues, type.c_str(), 0, 0);
	Util::LoadFromBuffer(keyValues, materialName.c_str(), materialData.str().c_str(), nullptr, NULL, nullptr);

	return pMaterial->CreateMaterial(materialName.c_str(), keyValues);
}`
createmove: `bool __stdcall hCreateMove(float frametime, CUserCmd* cmd) {

		auto result = ClientHook->GetOriginalFunction<CreateMoveFn>(22)(pClient, frametime, cmd);

		if (!cmd->command_number)
			return result;

		uintptr_t* framePointer;
		__asm mov framePointer, ebp;
		bool& sendPacket = *reinterpret_cast<bool*>(*framePointer - 0x34);

		pGlobalVars->serverTime(cmd);

		BHop::CreateMove(cmd);
		AutoStrafe::CreateMove(cmd);
		BHop::CreateMoveCircle(cmd);
		//Resolver::CreateMove(cmd);

		if (Settings::Misc::AntiAfk && cmd->command_number % 2)
		{ cmd->buttons |= 1 << 26; }	
			static void* oldPointer = nullptr;
			C_BasePlayer* localplayer = (C_BasePlayer*)pEntityList->GetClientEntity(pEngine->GetLocalPlayer());
			auto network = pEngine->GetNetChannelInfo();
			if (oldPointer != network && network && localplayer)
			{
				oldPointer = network;
				Backtrack::UpdateIncomingSequences(true);
				NetDataGram = std::make_unique<VMTHook>(network);
				NetDataGram->HookFunction(SendDatagram, 46);

			}
			Backtrack::UpdateIncomingSequences();
		
			GrenadeHelper::CreateMove(cmd);
			GrenadePrediction::CreateMove(cmd);

			Backtrack::run(cmd);
			Aimbot::CreateMove(cmd);
			Triggerbot::CreateMove(cmd);

			lbyindicator::CreateMove(cmd);		
			ReportBot::run();	
			ShowRanks::CreateMove(cmd);
			AutoDefuse::CreateMove(cmd);
			JumpThrow::CreateMove(cmd);
			EdgeJump::PrePredictionCreateMove(cmd);
			NoDuckCooldown::CreateMove(cmd);
			PredictionSystem::StartPrediction(cmd);
			Autoblock::CreateMove(cmd);
			NameChanger::fakeBan();
			AutoKnife::CreateMove(cmd);
			AntiAim::CreateMove(cmd);
			Airstuck::CreateMove(cmd);
			Fakewalk::CreateMove(cmd);
			MoonWalk::CreateMove(cmd);

			Walkbot::CreateMove(cmd);
			FakeLag::CreateMove(cmd);
			ESP::CreateMove(cmd);
			PredictionSystem::EndPrediction();
			
			AngleIndicator::PostPredictionCreateMove(cmd);
			EdgeJump::PostPredictionCreateMove(cmd);
	
		return false;
	}`
input: `public:

	inline CUserCmd* GetUserCmd(int sequence_number);
//	inline CVerifiedUserCmd* GetVerifiedCmd(int sequence_number);
	                                                  //should work -4 on all
	std::byte			pad0[0xC];			    // 0x0
	bool				m_fTrackIRAvailable;	// 0xC
	bool				m_fMouseInitialized;	// 0xD
	bool				m_fMouseActive;			// 0xE
	std::byte			pad1[0x9A];			    // 0xF
	bool				m_fCameraInThirdPerson;	// 0xA9
	std::byte			pad2[0x2];			    // 0xAA
	Vector				m_vecCameraOffset;	    // 0xAC
	std::byte			pad3[0x38];			    // 0xB8
	CUserCmd*           m_pCommands;                  //0xEC

	CUserCmd* GetUserCmd(int nSlot, int sequence_number)
	{
		return VirtualMethod::call<CUserCmd*, 8>(this, nSlot, sequence_number);
	}
};


CUserCmd* CInput::GetUserCmd(int sequence_number)
{
	return &m_pCommands[sequence_number % 150];
}
`

**Comment by Utkukck11** [comment]
S

**Comment by tylerdurdenc** [comment]
?
