### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by tylerdurdenc** [maikel233/X-HOOK-For-CSGO#9]
is it missing files or what? i keep getting a ton of erros about CSWeaponType
![image](https://user-images.githubusercontent.com/31171385/187087340-fe7abb63-f80d-45f5-b239-5350c2efeac9.png)
compiling it as debug/x86

**Comment by Utkukck11** [comment]
> is it missing files or what? i keep getting a ton of erros about CSWeaponType ![image](https://user-images.githubusercontent.com/31171385/187087340-fe7abb63-f80d-45f5-b239-5350c2efeac9.png) compiling it as debug/x86

Yeah he didnt uploaded some files i think also there errors on lobbymod too about keyvalues

**Comment by maikel233** [comment]
Ah i forgot to include some files... Try again

**Comment by Utkukck11** [comment]
> Ah i forgot to include some files... Try again

Thanks i will try

**Comment by tylerdurdenc** [comment]
Now it says Utils_fox.h cannot be included which prob is also missing
![devenv_oBKUBEUDRW](https://user-images.githubusercontent.com/31171385/187279520-8b754650-8d0f-4fb3-a028-9f08be11f172.png)

edit: fixed minhook and utils one but still has a lot of erros about google and proto files

**Comment by 2lag** [comment]
hes still missing a lot of the files, as you can see on the second line "cannot open source file '../Utils/minhook/Minhook.h" among the Utils_fox.h (which is actually included), but the protobuff ones will give you errors until you redefine the directory in the #include statement.

either way, missing files. please fix and/or include compilation/solution settings

**Comment by Utkukck11** [comment]
Also i get Errors from menu.cpp and lobbymod about player indicator and keyvaluesfunc not found

**Comment by tylerdurdenc** [comment]
> Also i get Errors from menu.cpp and lobbymod about player indicator and keyvaluesfunc not found

about menu.cpp just comment out the player indicator toggle and it should be fine
